modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "runes"
version = "${version}"
displayName = "Runes"
authors = "Daedelus"
credits = "Tutta (Artwork), Crispytwig (Artwork)"
description = '''
Craft runes to serve as ammo for spells.
'''
logoFile = "icon.png"

[[dependencies.runes]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.runes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.runes]]
modId = "fabric_api_base"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "runes.mixins.json"
