modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "runes"
version = "${version}"
displayName = "Runes"
authors = "Daedelus"
credits = "Tutta (Artwork), Crispytwig (Artwork)"
description = '''
Craft runes to serve as ammo for spells.
'''
iconFile = "icon.png"

[[dependencies.runes]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.runes]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_min_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "runes.mixins.json"
